### ISSUE TITLE
Remove duplicate code from dispatcher implementations

### ISSUE THREAD

**Issue by rjcanto** [i-on-project/integration#247] opened 2021-06-10 15:57 UTC
The `dispatch` method is duplicated in dispatcher implementations:

- ISELAcademicCalendarDispatcherImpl.kt
- ISELTimetableDispatcherImpl.kt

**Comment by grimord** [comment] 2021-06-23 21:47
Duplicate of #256. Closed by #257

**Closed as completed by grimord** 2021-06-23 21:47 UTC
Labels: enhancement
